### ISSUE TITLE
binding.js中报indexOf of undefined错误

### ISSUE THREAD

**Issue by yyg1219** [simo-an/better-clipboard#4]
在electron项目安装完成后，使用时报indexOf of undefined错误，请问这是为什么呢
![屏幕截图 2022-01-25 144045](https://user-images.githubusercontent.com/38304911/150925032-f0e2f8b5-37c4-4886-8bb6-8d5cdf11a7a7.png)

**Comment by simo-an** [comment]
![image](https://user-images.githubusercontent.com/38021707/150940907-888ecaaa-343d-4872-ba14-3b41c084b2d7.png)

我这边打印这个`fileName`输出的是`better-clipboard.js`的地址。

具体原因我也不知道。

我实现了一个最小版的样例，你看下能否跑起来：
https://github.com/simo-an/example-better-clipboard
